# DB
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=ENC(lrZM6ibtn0JPpletaK1qq6ZidHix169VCpnRHdtAnVDyZQTceYrzqIegh8wOqpoKoq1cqitRlVsjpt51RnTp7WeSqeXXN/IZsgQ8tbrZ9kA=)
spring.datasource.username=ENC(HS4uCZajObRmsJjNlK21Ois+WsvGAynfgB+NcgGmoedFymgMUkZDnEtWALw/rVna)
spring.datasource.password=ENC(CN6WAbNjQHGBS7lexFQsiaVDA6i1Ejcg8Oa9X3mqnaGczJz6SWmNjJu7VkDV/uyT)

logging.level.org.springframework.security=DEBUG

# 네이버 로그인
naver.client-id=ENC(mnuUny4meDbauItzyaRYWOcs6RcDizU7qYXUm5BOWSQoGx2p8mQ4l7X2nppoiH7oMZHDyvOIq7bBAJJeaU2tJg==)
naver.client-secret=ENC(es7WB0gUG0MSSYwHiDFD1McW68tutgmblSZ4GQIHZ6EkTp1+BgcIqkV1oXOYVJkV)

# 카카오 로그인

# default upload path
file.upload.base.path=D:/upload
file.upload.profile.path=${file.upload.base.path}/profile/
